on:
  push:
    branches: [dev, main]

name: email-cognito

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Extract Branch Name
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: List Files and Current Directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in the Directory:"
          ls -la

      - name: Build Package
        run: sam package --template-file ${{ github.workspace }}/template.yml --output-template-file ${{ github.workspace }}/packaged.yml --s3-bucket email-cognito-deploy

      - name: Deploy
        run: sam deploy --template-file ${{ github.workspace }}/packaged.yml --parameter-overrides Environment=${{ env.branch }} --capabilities CAPABILITY_IAM --stack-name email-cognito-stack-${{ env.branch }} --region us-east-2
